### ISSUE TITLE
missing numbers?

### ISSUE THREAD

**Issue by galicae** [nfi4l/python-homework#1]
I'm not sure that you can calculate powers without specifying the power itself, see [line 11](https://github.com/nfi4l/python-homework/blame/8102b977e8c7575824cd63ed63570c3933694d67/rosalind_exercises.md#L11) of the INI2 solution.

**Comment by nfi4l** [comment]
oh right whoopsies, I fixed it now

**Comment by galicae** [comment]
doesn't look fixed, did you forget to commit/push?
